---
title: "AAA"
editor: visual
code-block-bg: dark
---

## General Info

-   AAA = Authentication, Authorisation, Accounting
-   Who are they, what can they do, what did they do...
-   `if-authenticated` used in **authorisation** config to allow user to access exec session once authenticated if TACACS/RADIUS server not reachable.
-   `aaa new-model` - Enables AAA, also tells device to look at the local DB if no credentials configured under Con/VTY lines.

### Securing Line Access

-   Routers/Switches have Console (CTY), Virtual Terminal (VTY) and occasionally AUX ports for access.

-   Securing Console

    ``` default
    Line Con 0
    Login                               
    password [password]                        !!! This secures the console line, in this case, with only the password [password]. NOTE-if Enable password is configured this will be required to get to priv exec mode.
    !
    !
    Line Con 0
    Login Local                                !!! Login Local - tells switch to look at local user database
    !
    !
    Line Con 0
    Login Authentication [Method List]
    transport input SSH                       !!! Enables SSH (disables Telnet)
    ```

### Securing with ACL's

-   **IP access-list**: Defines traffic - either via permit/deny
-   **Access-group**: applies an ACL to a physical `interface`
-   **Access-class**: applies an ACL to a `line` (VTY, Console, Aux) etc.

### **Configuration**

``` default
username [user] privilege 15 secret [password] 
!
aaa new-model
aaa group server tacacs+ [group]
 server-private 10.44.155.20 single-connection key [key]
 ip vrf forwarding Mgmt-intf
 ip tacacs source-interface GigabitEthernet0
!
! Alternate Method of server config with single server^
!
tacacs server [server]
 address ipv4 [10.44.241.250]
 key [passkey]
aaa group server tacacs+ [group-name]
 server name [server]
 ip tacacs source-interface GigabitEthernet0
!
aaa authentication login [method list] group [group] local
aaa authorization exec [method list] group [group] local if-authenticated
aaa authorization commands 15 [method list] group [group] local if-authenticated
aaa accounting commands 1 [method list] start-stop group [group]
aaa accounting commands 15 [method list] start-stop group [group]
aaa session-id common
!
! using method list 'default' applies the AAA methods to all lines 
!
line vty 0 4
login authentication [list-name]


***
aaa authorization exec default local          - Puts authenticated user to priv exec upon login]
line vty 0 4
  authorization exec default
  
To use AAA on console port this is also required
line con 0
  logging authentication [group]
  aaa authorization console
  
```

## 

## Useful show commands

-   `show ip interface g0/0 | include List` - Shows ACL's + direction applied to interface.
-   `debug aaa authentication` - Debug all AAA auth
-   `debug radius authentication` - Debug for radius auth
-   `debug tacacs authentication` - Debug for tacacs auth
-   `debug aaa protocol local` - Debug local authentication
-   
