---
title: "BGP"
editor: visual
code-block-bg: dark
---

# General Info

-   Used **TCP 179** **to** establish session. Unicast
-   Admin Distance: iBGP AD = **200**, eBGP AD = **20**
-   Use of TCP allows for adjacencies with non directly connected neighbour.
-   Only **Best route** + **next hop** are advertised, not all routes.
-   Multi-hop session require underlying routes from RIB (dynamic or static) Must explicitly configure neighbour relationships
    -   TCP session established
    -   Advertises Address Prefix & Length (called Network Layer Reachability Information - NLRI)
-   Hold Time: **180s**, Keepalive: **60s** (1/3 ratio)
    -   Adjust under bgp process with `timers bgp 5 20` - keepalive 5 / hold 20
-   Uses Address families to
-   AFI/SAFI - Address & Subsequent Address Family Identifiers (ipv4 unicast etc).
-   Modern BGP sets DF bit (do not fragment) to prevent fragmentation.
-   BGP RID - If not manually configured (which is recommended)
    -   Highest IP on Loopback int that's up
    -   Highest IP on any other Interface thats up
-   BGP Synchronisation - disabled on modern devices by default
    -   RULE: Only advertise routes learned from iBGP peer to an eBGP peer when there is an exact match of that route learned from an IGP in the routing table.
-   **iBGP**
    -   TTL = 255
    -   Uses split horizon for loop prevention, requires full mesh of BGP routers inside single AS
        -   A route learned from 1 iBGP won't be forwarded to another iBGP peer by default.
        -   This can be overcome with route-reflectors
    -   NRLI's from iBGP peer can only be forwarded to eBGP peer.
-   **eBGP**
    -   TTL = 1, this can be increased using `neighbor [ip] ebgp-multihop [1-255]`
    -   Can also use `neighbor [ip] ttl-security hops [hop-count]`
    -   Difference = `eBGP-multihop` = sets *maximum range* allowed, `TTL-security` sets *exact range*
-   If peering with different update source but not through additional hops, can use `neighbor <ip> disable-connected-check`
-   Does change next-hop by default
-   It's recommended to update source to a loopback for resiliency `neighbor [ip] update-source [loopback]`
-   NRLI from eBGP can be shared onto all other peers.
-   **Peer groups**
    -   Can be used when multiple neighbors have the same requirements
    -   Use `neighbor <name> peer-group` to set up peer-group, then perform config under `neighbor <name> <command>`
    -   Peer groups applied to neighbor with `neighbor <ip> peer-group <name>`
    -   Can check with `show ip bgp peer-group`
    -   Peer groups are natively set up on the back end to limit CPU usage - only purpose is simplification of config
-   **ECMP**
    -   Can enable load-balancing with `maximum paths <path#>` command

    -   Only takes effect when many parameters on routes match - Weight, local preference, AS-PATH (both numbers and lengths), origin code, MED, IGP metric

    -   use `maximum-paths <value>` to enable multipath load sharing for eBGP

    -   use `maximum-paths ibgp <value>` to enable for iBGP

    -   use `maximum-paths eibgp <value>` to enable for iBGP & eBGP

    -   

# Features/ Attributes

Cheat sheet - [https://ipcisco.com/wp-content/uploads/Cheat-Sheets/bgp.pdf](https://ipcisco.com/wp-content/uploads/Cheat-Sheets/bgp.pdf){target="_blank"}

## Path Selection

**W**e **L**ove **O**ranges **AS** **O**ranges **M**ean **P**ure **R**efreshment or NWLLA OMNI - Next Hop

1.  **W**eight (Highest)
2.  **L**ocal Preference (Highest)
3.  **O**riginated locally
4.  **AS**\_PATH (Shortest)
5.  **O**rigin code (IGP \> EGP \> ?)
6.  **M**ED (Lowest)
7.  **P**ath (eBGP \> iBGP)
8.  IGP metric (Lowest)
9.  Route age (Oldest, only compared when routes from different eBGP peers)
10. RID (Lowest)
11. Choose path with minimum cluster list length
12. Choose path through neighbour with lowest IP address

## Path Selection 2 (NWLLA OMNI)

1.  Next Hop must be Reachable
2.  Weight (Highest)
3.  Local Preference (Higher)
4.  Locally Originated
5.  AS_PATH (Shortest)
6.  Origin Code (Prefer i\>e\>?)
7.  MED (Smaller Preferred)
8.  Neighbour Type - prefer eBGP over iBGP
9.  IGP Metric to next hop - (Smaller)

## Route Reflector

-   Allows route learned from iBGP neighbour can be reflected to neighbours in same ASN - negates need for full mesh
-   Configured using `neighbour [ip] route-reflector-client` on the route reflector
-   3 rules:
    -   Routes learned from eBGP peers can be sent to other eBGP peers, clients, and non-clients.
    -   Routes learned from client peers can be sent to eBGP peers, other client peers, and non-clients.
    -   Routes learned from non-client peers can be sent to eBGP peers, and client peers, *but not other non-clients*.
-   `next-hop-self` only affects eBGP routes when used with route reflectors.
-   [**Originator_ID & Cluster_ID**]{.underline} attributes added to reflected routes for loop prevention

## Summarisation

-   Configured on AS Edge Routers
-   Can use `auto-summary` however this only summarises classful networks
-   Configured with `aggregate-address 10.0.0.0 255.0.0.0 [summary-only] [as-set]`
    -   use of `summary-only` advertises only summary route, not the aggregated networks
    -   use of `[as-set]` carries over AS_Path attributes from component routes. (disordered AS's in Curly brackets)
-   These routes are assigned the ***ATOMIC_AGGREGATE*** attribute to indicate they are aggregates & that loss of path info has occurred.
-   The summarising router adds an entry in their RIB with destination Null0 to avoid loops.
-   AS_Path, MED +communities aren't included in new prefix info
-   Can include AS_Path info using `as-set`

## **BGP regexp**

-   Can be used to search for specifc AS-PATHs in table - for example: `show ip bgp regexp ^$` this shows entries where AS-PATH is empty (locally originated)
-   Above will show prefixes originated locally with the AS. Cheat sheet [here.](http://gponsolution.com/bgp-regular-expressions-cheat-sheet.html)
-   Originated in AS 100: `_100$`, Learned from AS 100: `^100_` , Locally Originated `^$`
-   Can be used to filter with ACLs with IP as-path: `ip as-path access-list 1 permit _54$`
-   Then use `match as-path` under a route-map to apply modifications
-   TIP: Summarise Address without using aggregate-adresss
    -   Create static route for the summarised address with destination Null0

    -   Redistribute Static under the BGP precess.

## Next Hop Reachability

-   eBGP: next-hop IP address is updated by the advertising router.
-   iBGP: next-hop IP is not changed but is configurable.

# BGP Attributes (Main)

## **Weight**

-   Only used on the router where it is configured
-   Used to affect outbound routing.
-   Higher value is better - default is 0 (32768 if originated locally)
-   Highest in BGP path selection algorithm
-   Cisco proprietary
-   Configuration:

``` default
route-map SET_WEIGHT  
 match ip address|ip as-path ...  
 set weight 100 
! 
router bgp 100  
 neighbor <ip> route-map SET_WEIGHT in  
!  
 neighbor <ip> weight <weight> 
```

## **Local Preference**

-   Locally significant (to the AS), does not transit outside AS.
-   Used to affect outbound routing.
-   Higher value is better - defaults to 100
-   Configuration:

``` default
route-map SET_LP  
 match ip address|ip as-path ...  
 set local-preference 1000  
! 
router bgp 100  
 neighbor <ip> route-map SET_LP in  
 !  
 bgp default local-preference <locpref>
```

## **AS-PATH**

-   Changed for each AS prefix transits through
-   Used to affect inbound routing
-   Can be used to influence path selection with as-path prepending
-   Can be ignored with `bgp bestpath as-path ignore` - this is dangerous and not recommended
-   Can be limited in length with `bgp maxas-limit <#>`
-   Configuration:

``` default
route-map PREPEND
 match ip address|ip as-path ...  
 set as-path prepend 100 100 100     
! 
router bgp 100  
 neighbor <ip> route-map PREPEND out
```

## **Origin Code**

-   Rarely used to influence path selection - inflexible
-   IGP \> EGP \> Incomplete
-   Could affect inbound or outbound routing
-   Configuration:

``` default
route-map ORIGIN 
match ip address|ip as-path ...  
set origin [igp|egp|incomplete]  
!
router bgp 100  
neighbor <ip> route-map ORIGIN out
```

## **MED**

-   By default only compared when originating from same AS
-   Lowest is best - defaults to 0
-   Used to affect inbound routing
-   Can use `bgp always-compare-med` under router BGP to allow comparison of MED between different ASs
-   Configuration:

``` default
route-map MED 
match ip address|ip as-path ...  
set metric 1000      
router bgp 100  
neighbor <ip> route-map MED out
```

------------------------------------------------------------------------

# BGP Configuration

`bgp redistribute-internal` - all BGP routes redistributes

``` default
router bgp 100
 bgp router-id 4.4.4.4
 ! iBGP Neighbor
 neighbor 150.1.1.1 remote-as 100
 neighbor 150.1.1.1 update-source loopback0
 neighbor 155.1.1.1 route-reflector-client
 neighbor 155.1.1.1 next-hop-self # will only affect eBGP routes for RR clients
 ! eBGP Neighbor
 neighbor 150.1.3.3 remote-as 200
 neighbor 150.1.3.3 update-source loopback0
 neighbor 150.1.3.3 ebgp-multihop
 neighbor 150.1.3.3 send-community both
 neighbor 150.1.3.3 route-map FROM_R3 in
 neighbor 150.1.3.3 route-map TO_R3 in
 !
 network 155.1.4.0 255.255.255.0 route-map SET_COMMUNITY_50
 network 150.1.4.0 255.255.255.0
!
ip prefix-list BGP_PREPEND_1 seq 5 permit 150.1.4.0/24
!
ip prefix-list DEF
LT seq 5 permit 0.0.0.0/0
!
route-map FROM_R3 deny 10
 match ip address prefix-list DEFAULT
!
route-map FROM_R3 permit 10000
!
route-map TO_R3 permit 10
 match ip address prefix-list BGP_PREPEND_1
 set as-path prepend 100 100 100 100
!
route-map TO_R3 permit 10000
!
route-map SET_COMMUNITY_50 permit 10
 set community 50
```

------------------------------------------------------------------------

# Useful Show Commmands

-   `show bgp ipv4 unicast` - shows the bgp table
-   `show bgp ipv4 unicast neighbors 10.1.1.2 advertised-routes` - shows which routes are being advertised to neighbour 10.1.1.2
-   `show bgp ipv4 unicast summary` - shows exchange of routes between nodes
-   
