---
title: "EIGRP"
editor: visual
code-block-bg: dark
---

# General

-   Distance/Vector protocol
-   Classic/Named Mode
    -   Classic: Commands under router process + Interfaces - disparate.
    -   Named: Config in SubSections - Address Family, Interface & Topology
-   AD 90 internal, 170 External
-   **Hello**'s are Multicast on **224.0.0.10**, port **88**
-   Timers
    -   Hello - default 5 secs, (60 on Slow interfaces)
    -   Hold - default 15 secs, (180 on slow interfaces) - How long we tell neighbour to wait for us.
-   Load balance over unequal paths using `variance` (multiple of FD) - only IGRP that can do this.
-   Uses K Values for Metrics (K1-5, Bandwidth, Delay, Reliability, Load, MTU) - set with `metric-weights`
    -   Mostly uses
        -   K1 - Bandwidth - slowest in path
        -   K3 - Delay - cumulative
-   Supports VLSM by sending mask
-   Can configure neighbour specifically to use **Unicast**
-   Uses RTP (reliable transport protocol - confirms messages neighbour received messages but not hello)
-   Uses DUAL (Diffusing identifies neighbour with lowest Feasible Distance)
    -   FD set to **Infinity** to indicate the router is in transition & seeking alternative paths
-   3 Data Structures
    -   `Neighbour Table` - Who our EIGRP neighbours are
    -   `Interface Table` - which interfaces are participating
    -   `Topology Table` - shows routes known to EIGRP
-   Router-ID configurable - if not generated by highest configured + active Loopback, then any IPv4 interface.

# Features

##### Neighbourship

-   **Autonomous System** number **must match** between Neighbours
-   Hello + Hold don't have to be identical (Hold typically 3x the Hello)

##### Path Selection

-   **Reported Distance** - cost to destination from neighbouring router
-   **Feasible Distance** - RD + path cost to get to neighbouring router.
-   **Successor Route** - the lowest cost path to route
-   **Successor** - First Hop route on that path
-   **Feasibility Condition** - That the **RD** must be less than the **FD** (loop prevention)
-   **Feasible Successor** - route which passes the feasibility condition.

------------------------------------------------------------------------

##### Authentication

-   Supports plaintext + hash based auth - MD5 & SHA-256 auth (named) or just MD5 (classic)
-   MD5 configuration done with key chain in global config
    -   `key-string` must match but the `key chain` name doesn't have to (but it makes sense if they do!)
-   Key-id numbers must match for successful auth
-   Applied under physical interfaces in classic mode or af-interfaces in named mode

``` default
key chain MD5_KEYS  
 key 1   
   key-string MD5_PASS 
! 
router eigrp MULTI-AF  
!  
 address-family ipv4 unicast autonomous-system 100   
  !  
  af-interface default    
   authentication mode hmac-sha-256 SHA_DEFAULT  
  exit-af-interface   
  !   
  af-interface GigabitEthernet1.58
  authentication mode md5    
  authentication key-chain MD5_KEYS   
  exit-af-interface
  
In classic
int g0/0
 ip authentication mode eigrp 10 md5
 ip authentication key-chain eigrp 10 MD5_KEYS
```

##### Route Filtering

-   Can be advertised with quad 0 summary route under interface

-   Can also be redistributed from static route

-   Use of Distribute-list stops route being added to topology & routing table - `distribute-list prefix [prefix-list] [in/out] [interface]`

-   Can also use route-maps to match on tags, metric

    -   For example:

    ``` default
    route-map FILTER_ON_TAGS deny 10  
      match tag 4 
    ! 
    route-map FILTER_ON_TAGS permit 20 
    ! 
    router eigrp 100
      distribute-list route-map FILTER_ON_TAGS in
    ```

##### Loop Prevention

-   Split-Horizon - stops a route being learned on the interface it was advertised on.
-   Use of Feasibility condition.
-   Can disable on P2P link - `no ip split-horizon eigrp [AS]`

##### Redistribution - see redistribution

-   see [Redistribution Page](https://kolkrabe.github.io/notes/redistribution.html)

##### Summarization

-   Possible anywhere in topology
-   Manual or Auto (auto is classful).
-   Configured with `summary-address <network> <mask>` under af-interface in named mode, under physical interface in classic mode
-   Leak map can be used to leak longer mask prefixes included in summary
    -   `summary-address 0.0.0.0 0.0.0.0 leak-map <route-map>`
-   "Discard Route" installed with destination Null0 - match summary address to prevent loops (AD set to 5)
-   Can define metric on summary-address with the `summary-metric` command under topology base

##### Stub

-   Prevents advertisement of anything other than connected routes + summary routes *by default*
-   If route goes active the router doesn't send EIGRP Queries to Stub
-   Prevents site from being used for transit
-   Breaks query domain
-   Best used when sites have no downstream neighbors
-   Can use leak-maps to advertise normally suppressed routes

##### Stub Site

-   Only on named mode
-   Allows advertisement of routes learned on LAN but not WAN interfaces
-   Limits EIGRP query-domain and prevents site from being used for transit
-   Enabled with `eigrp stub-site`
    -   Mutually exclusive with `eigrp stub`
-   Interfaces towards hub/WAN identified with `stub-site wan-interface` under af-interface

##### Split Horizon

-   Prevents route being advertised out of the interface they were learned from.
-   Stops routing loops
-   Can be disabled `no ip split-horizon eigrp [AS]` - Useful for Hub & Spoke networks

##### Load balancing

-   In named config configured under `Topology base`
-   Equal cost load balancing enabled by default (max 4 paths by default)
    -   alter max number of equal cost/metric routes using `maximum-paths [x]`
-   Variance used to enable load balancing between unequal paths, installs feasible successor routes and puts them into the routing table
-   variance is a multiplier of Feasible Distance. Verify (and show traffic share) with `show ip route [network]`

##### Metrics

-   wide-metrics - used to scale EIGRP for modern bandwidths, NAMED Mode only.
-   Introduces K6 value.
-   configure under address family

##### Offset-lists

-   Used for traffic steering
-   Can modify path attributes based on *direction of update* / *PREFIX* / combination of both.
-   Can be used to increase metric for a specific route/interface
-   Configured under topology base (modifying metric) with for Modern / Under process for Classic
    -   `offset-list [access-list] [in/out] [metric] [interface]`

##### EIGRP for IPv6

-   Doesn't use Network command

-   Protocols enabled at the interface-level

-   Still requires manual creation of a global eigrp routing process, uses 32bit Router-ID

    ``` default
    ipv6 unicast-routing
    !
    int g0/0
      ipv6 address 2001:1234:1234:1234::4/64
      ipv6 eigrp 100
    !
    ipv6 router eigrp 100
    ```

------------------------------------------------------------------------

## EIGRP - Traditional IPv4 Configuration

``` default
CLASSIC
router eigrp 10 
network 10.1.1.0 0.0.0.255           - If any interfaces match & configured/up they should participate in EIGRP
network 172.16.1.0 0.0.0.3
network 0.0.0.0 255.255.255.255      - Makes all interfaces participate in EIGRP
  interface G0/1
    ip hello-interval eigrp 10 3
    ip hold-interval eigrp 10 15
    timers active-time 2
eigrp stub                            - for stub site

---

MODERN
router eigrp [NAME]
 !
 address-family ipv4 unicast autonomous-system 1
 eigrp stub                           - for stub site
  !
  af-interface default
   passive-interface                 - Sets all intefaces as passive.
   ip hello-interval eigrp 10 3       - Can be here or af-interface section below
   ip hold-interval eigrp 10 15
  exit-af-interface
  !
  af-interface GigabitEthernet0/1
   no passive-interface               - enables interface for EIGRP
   ip hello-interval eigrp 10 3
   ip hold-interval eigrp 10 15
  exit-af-interface
  !
  topology base
  variance 2
    timers active-time 2              - 3 mins by default, 
  exit-af-topology
  network 10.1.1.2 255.255.255.255
  m
  eigrp router-id 150.1.5.5
 exit-address-family
```

## Useful Show Commands + Info

-   `show ip route EIGRP` - shows EIGRP routes installed into the RIB

-   `show ip eigrp interfaces` - shows active EIGRP interfaces

-   `show ip eigrp interfaces detail` - shows detailed interface info (hold time, split-horizon enabled etc.

-   `show ip eigrp topology all-links` - shows all additional paths to network (failed Feasibility Condition)

-   `show ip protocols` - displays EIGRP process ID, ASN, K values, RID, Neighbours, AD + Passive Ints

-   Stuck in Active - router sends query about network, doesn't hear back and thinks it's neighbor has died. Default timer 3 mins, router waits half then sends SIA query to neighbours

-   EIGRP routes with same `router-id` will form an adjacency but won't accept routes from one another. Investigate using `debug ip eigrp`

-   `show ip eigrp traffic` - shows traffic statistics - \# of hellos, updates, queries, replies etc.
