---
title: "Misc"
editor: visual
code-block-bg: dark
---

SPT Loopguard protects against L2 loops, enabled per port.

-   If non designated port stops receiving BPDUs, loopguard moves the port to "STP Loop-inconsistent blocking state, rather than listening/learning/forwarding which would cause a loop.
-   Once BPDU received again the port is transitioned and doesn't require intervention.

DHCP Option 82 - Relay Agent Information Option

-   Increases DHCP security by enabling identification of request sources and,
-   allows address allocation based on network topology or client device characteristics.
-   When DHCP Snooping + IP Source Guard enabled - DHCP server must support option 82.
    -   Enable: `ip dhcp snooping information option`

DHCP Option 66 - next-server option - ip/hostname of TFTP or HTTP server for client to download files from.

OSPF - Advertising Loopbacks - default mask /32, to show the configured subnet mask change the loopbacks network type to **"point-to-point"**

Route Target - Appended to VPNv4 BGP route to indicate membership MP-BGP VPN

Route Distinguisher - Pre-pended to IP Address to create globally unique VPNv4 Address

Logging Synchronous All - Unsolicited messages appear after solicited.

`aaa authorization console` is disabled by default

By default, only internal OSPF routes are redistributed into BGP

SNMP - `snmp trap link-status permit duplicates` - generates traps when link is flapping chronically. **MUST** be configured on interface

``` default
interface g0/0
 snmp trap link-status permit duplicates
```

Log Timestamps - when no log/debug keyword specified (`service timestamps`) - it's like issuing `service timestamps debug uptime` applied be default - shows **UPTIME**

BGP learned route RIB Failure (r)

1.  We have a better route in our routing table (static perhaps)
2.  We can't reach the next hop associated with that route (neighbour advertising route with different next hop that itself. )

LDP Extended Discovery Message - Unicast message used to find and establish session with LDP Neighbour (LSR) not directly reachable via multiast hello's.

`debug CEF interface` - debugs events related to CEF

-   Planes

    -   Management Plane - Anything which is used to manage the device
    -   Data Plane - switching frames/routing packets.
        -   Services Plane (Subset of Data) - facilitates encapsulation of user data into tunnels (QoS, MPLS VPNs, IPSec Tunnels, GRE Tunnels)
    -   Control Plane - Controls that facilitates the learning of destinations, prefixes, MAC Addresses (IP/IPv6 addresses, MAC, ARP, IPv6 Neighbour discovery)

-   BGP: does NOT reapply policies to existing routes automatically when you apply or change the following. (Only new updates are affected).

    -   route-map
    -   prefix-list
    -   filter-list
