---
title: "OSPF"
editor: visual
code-block-bg: dark
---

# General Notes

-   Link State Routing Protocol - makes routing decisions based on the state of links.
-   Once adjacency formed each router has the same **Link State Database.**
-   Reacts only to changes, no constant flooding of updates.
-   AD - 110 for Internal & External
-   Process-ID - **Locally** significant.
-   Timers (Default - dead = 4 x Hello)
    -   Hello - 10
    -   Dead Interval - 40 (How long local router waits to hear neighbours Hello
    -   Wait Timer - 40 (How long to wait for DR/BDR to be elected before triggering election)
    -   Retransmit - 5 (how long to wait to retransmit OSPF packet which hasn't been acknowledged)
-   224.0.0.5 - Broadcast for All OSPF Routers (Broadcast), **Port 89**
-   224.0.0.6 - Broadcast for All Designates Routers, **Port 89**
-   **DR/BDR Election** - Highest Priority value (0 to remove from election) - Highest Router-ID - Highest IP on Loopback Int - Highest IP on interface that's UP
-   **Metric Calculation**
    -   Bandwidth \\ References Bandwidth - Default ref is 100Mb (all interfaces \> 100M have same ref cost.
        -   Change ref bandwith with `auto-cost reference bandwidth [value]` big kev recommends 2TB!
        -   Should match across topology but won't stop neighbourships forming.
-   Network Type (don't have to match)
    -   Broadcast - ethernet -Default for OSPF - DR/BDR
    -   Point-to-Point - Default for non-Frame Relay serial interface, no DR/BDR required
    -   NBMA - Frame Relay - DR/BDR required, no broadcasts or multicasts, Neighbours must be manually configured. (Hello 30 seconds)
    -   Point-to-Multipoint - No DR/BDR required, hello 30 secs
    -   When mixing - might have to adjust timers.
-   **LSAs**
    -   **Type 1 - Router LSA** (Intra-Area)
        -   Generated by **all OSPF routers**, area local scope, shares directly connected neighbours
    -   **Type 2 - Network LSA** (Intra-Area)
        -   Generated by **DR**, area local scope, describes DR adjacent routers.
    -   **Type 3 - ABR Network Summary LSA** (Inter-Area)
        -   Generated by **ABR,** sends list of networks in adjacent area, one LSA per network.
        -   Default route sent using Type 3 LSA
    -   **Type 4 - Summary ASBR LSA**
        -   Generated by **ABR,** tells members of an area how to reach ASBR.
    -   **Type 5 - External LSA**
        -   Generated by **ASBR,** network wide, goes to all non-stub areas.
        -   Describes routed the ASBR is redistributing.
        -   Type 1=E1 - Cost the ASBR reports plus cost to ASBR
        -   Type 2=E2 - Cost of Redistribution metric only, if tie-break cost to ASBR included.
    -   **Type 7 - NSSA External LSA**
-   Troubleshooting - **TAN MAT** (**T**imers, **A**rea, **N**etwork Address, **M**TU, **A**uth, **T**ype)

------------------------------------------------------------------------

# Features

## Neighbourship

-   Neighbourship Requirements (Must match)
    -   Matching Area
    -   Matching Auth Parameters
    -   Matching Subnet
    -   Matching Timers
    -   Matching Stub Flags
    -   Matching MTU (Exstart/Exchange State)
-   Troubleshooting - **TAN MAT** (**T**imers, **A**rea, **N**etwork Address, **M**TU, **A**uth, **T**ype)

## Authentication

-   Enabled per Interface or for all interfaces in an area
-   Plain text (pointless)
-   MD5 Hash - combination of key value + password. (Key + Password must **both** match).
-   HMAC with SHA (requires key chain)

``` default
PLAINTEXT (AREA)
router ospf 1
area [area id] authentication                               - Enables plaintext auth in the area specified
  int g0/1
    ip ospf authentication                                  - Or here Plaintext
    ip ospf authentication-key [password] 


MD5 (AREA)
router ospf 1
area [area id] authentication message-digest                - enables MD5 in the area specified
  int g0/1
    ip ospf authentication message-digest                   - Sets MD5 auth for that interface
    ip ospf message-digest-key [key#] md5 [password]        - Creates hash using key + password 
    
-------------------------------------------------------------------------------------------------------------

OSPFv3
area 0 authentication ipsec spi [value] sha1 0 [40char key]
int g0/0
  ospfv3 authentication ipsec spi [value] sha1 0 [40char key]



WITH KEY CHAIN
key chain OSPF_KEY
 key 1
  key-string [password]
  cryptographic-algorithm hmac-sha-256
ip ospf authentication key-chain OSPF_KEY
```

## Virtual Links

-   Allows adjacency with non directly connected neighbour between one ABR + multi Area Router
-   Configured with `area [transit area#] virtual link [neighbour RID]`
-   RID used rather than Router int IP.
-   Links shows as "DNA" in OSPF DB - 'Do Not Age' - reduced traffic flowing over link - no hello or refresh messages.
-   At least one device must be in Area 0, can't be formed in any stubby areas.

## Summarisation

-   Summarisation only possible at ABR + ASBR
-   Inter-Area Summarisation, reduces Type 3 LSAs, summarised metric = lowest metric of networks by default
    -   configured with `area [area-id] range [network + mask] cost [metric]` under OSPF process.
-   can use `not-advertise` to prevent prefixes being advertised
-   External router summarisation ndefined at ASBR
    -   configured with `summary-address [network + mask]` under OSPF process.
-   "Discard Route" installed with destination Null0 - matches summary address to prevent loops (AD set to 110 for internal, 254 for external

## Stub Areas

-   Blocks LSA Types 4 (ASBR) and 5 (External)
-   My ABR originates default route as Type 3 LSA, ABR can reach ASBR and ASBR can reach external route so I don't need details of external route & ASBR.
-   Can't redistribute any prefixes from within a Stub Area
-   Configured with `area [area #] stub`

## Totally Stubby Area

-   Blocks LSA Types 3 (Inter-Area), 4 (ASBR) and 5 (External)
-   Cisco Propriety
-   configured with `area [area #] stub no-summary` on ABR, other routers in area as above.
-   Default route tuning: `area [area #] default-cost [metric]`

## NSSA

-   Not So Stubby Area, RFC1587 (<https://www.ietf.org/rfc/rfc1587.txt>)
-   Two types, NSSA and totally NSSA
    -   NSSA prevents LSA5 advertisements but allows redistribution of externals

        -   Configured with `area <area#> nssa` under router ospf
        -   Does not advertise default route from ABR by default
        -   Can use `area <area#> nssa default-information-originate` to advertise default

    -   Totally NSSA prevents LSA3, 5 but allows redistribution of externals

        -   Configured with `area <area#> nssa no-summary` under router ospf
        -   Advertises default route from ABR
-   Externals originated in these areas will be LSA7s instead of LSA5s, translated to LSA5 at ABR

## Default Route

-   Configured with `default-information originate [always]`

-   Use of `always` advertises the default route even if one doesn't exist in the routing table.

## Filtering

-   Inter-area filtering possible only at ABRs, filtering Type 3 LSAs
-   Performed with `area <area#> filter-list prefix [prefix-list] [in|out]` - IN (filter against things into this area), OUT (Change area, filter out of this area)
-   Inter-area filtering also possible with `area [area  #] range [network] [mask] not-advertise` - area# is source area, can only be used at source ABR (looks are router/network LSAs)

``` default
ON ABR
ip prefix-list BLOCK_GLASGOW seq 5 deny 10.44.1.0/24 le 30         - deny this network with mask less than 30
ip prefix-list BLOCK_GLASGOW seq 10 permit 0.0.0.0/0 le 32         - permit everything else

router ospf 2
  area 1 filter-list prefix BLOCK_GLASGOW in                       - Blocks 10.44.1.0/24 from being advertised IN to area 1
  
```

-   Can also use distribute lists which stop the route being added to the routing table but **not the OSPF database. - CAN BE DONE ANYWHERE**

-   Configured using `distribute-list prefix [name] [in/out] [interface]`

```` default
### ACL
access-list 1 deny 28.0.0.0 0.255.255.255
access-list 1 permit any
!
router ospf 1
      distribute-list 1 in 
    ```

###  Example with Prefix List
PREFIX-LIST
ip prefix-list BLOCK_GERMANY deny 10.49.1.0/24 le32
ip prefix-list BLOCK_GERMANY permit 0.0.0.0/0 le 32
!
router ospf 1
distribute-list prefix BLOCK_GERMANY in
````

-   Can match on many values with route-maps, such as interface, ip address, ip next-hop, ip route-source, metric, route-type and tag

``` default
access-list 3 permit 155.1.146.0 
access-list 4 permit 155.1.0.4 
!
route-map DENY_VLAN146_FROM_R4 deny 10
 match ip address 3  
 match ip next-hop 4 
!         
route-map DENY_VLAN146_FROM_R4 permit 20 
! 
router ospf 1  distribute-list route-map DENY_VLAN146_FROM_R4 in
```

-   Note again distribute-lists **ONLY AFFECTS LOCAL RIB**, not OSPF database
-   Easy to create traffic black holes if not careful with this feature

Intra Area preferred

Inter Area next

Intra AREA

## OSPFv3

-   Requires `ipv6 unicast-routing` to be enabled in **Global Configuration** mode.
-   OSPF process enabled with `ipv6 ospfv3 <process>`
-   Issue `ipv6 address xx` or `ipv6 enable` command in **interface Configuration** mode
-   Issue `ipv6 ospf <process-id> area <area-id> [instance instance-id]` under **interface Configuration** mode
-   Note, if you don't enter a **RouterID** and there are no up interfaces the process will fail to start.
-   OSPFv3 Comms within a local segment based on **link-local** addresses.

------------------------------------------------------------------------

# Useful commands

-   `show ip protocol` - shows general info on active routing protocols
-   `show ip ospf` - shows detailed info on OSPF protocol, timers, metric etc.
-   `show ip ospf interface [brief]` - shows detailed/brief info on OSFP enabled interfaces, hold/wait timer etc.
-   `show ip ospf database` - shows the OSPF database for this area
-   `show ip ospf database summary self-originate` - shows the Type 3 LSA's generated by the ABR.
-   `show ip ospf neighbour [detail]` - shows list of OSPF neighbours plus states
-   `show ip ospf database router self-originate`
-   `debug ip ospf adj` - debugs OSPF adjacency
-   `debug ip ospf packet` - debugs all OSPF packets
-   `show ip ospf database router self-originate` - Useful to see routes advertised by local device
-   `show ip ospf virtual-links`

------------------------------------------------------------------------

# OSPF Configuration

``` default
router ospf 1                             - Process ID is locally significant
 router-id 1.1.1.1                        - Not an IP, just an ID.
 network 192.168.1.0 0.0.0.255 area 0     - Advertise interface within this network
 passive-interface default                - stops neighbour adjacency forming.
 no passive-interface gig 0/1             - int participates in ospf  

OR
 
int g0/2
ip ospf network point-to-point
ospf 1 area 0


ADDRESS FAMILIES
ipv6 Unicast-Routing                    !!!! Must enable this

router ospfv3 1
router-id 1.1.1.1
passive-interface g0/1
address-family ipv4
address-family ipv6
int g0/1
  ipv6 address 2001:CAFE::0/128         
  ospfv3 1 ipv4 area 0                
  ospfv3 1 ipv6 area 0
  ospfv3 1 hello-interval X
  ospfv3 1 hello-interval y
i

-----------------------------------------------------------------------------------------
Traditional ipv6 Config

ipv6 unicast-routing
!
ipv6 router ospf [process-id]
router-id [id]
passive-interface l0
no passive-interface l0

** Under OSPF Int *** 
interface g0/0
 ipv6 ospf [process-id] area [area-id]
```
