---
title: "Redistribution"
editor: visual
code-block-bg: dark
---

## General Info

-   Configured under Destination Protocol, specifying source protocol.
-   Redistribution is **NOT** transitive on a single router.
    -   R1 redistributes protocol 1 into protocol 2 and protocol 2 into protocol 3 - p3 won't receive P1's routes.
-   Redistribution between EIGRP to EIGRP or OSPF to OSPF preserves the path metrics
-   Sequential Protocol Redistribution is possible
    -   Redistribution over multiple protocols using multiple routers.
-   Routes must exist in RIB
-   Seed metric used to allow calculation of metric from Source Protocol
    -   EIGRP/RIP = Infinity (not installed into EIGRP topology table
    -   OSPF = 20 (1 for BGP)
    -   BGP = Uses IGP metric
    -   RIP = Needs a metric
-   `redistribute {connected | static | eigrp AS number | OSPF Process ID  [match {internal | external [1|2] } ] | BGP AS-number} [destination-protcol-options] [route-map RM NAME]`
-   Into OSPF = `subnets` allows classless networks to be redistributes

------------------------------------------------------------------------

## Per Protocol Info

### EIGRP

-   Redistribution configurable anywhere in topology
-   Redistributed routes marked as External (AD 170)
    -   If from another routing protocol
    -   OR, a redistributed **Static Route**
-   Default Metric = Infinity so not installed, **MUST** configure metric as follows for OSPF/BGP redist, not required for static + connected
    -   Set under router EIGRP config
    -   under address-family config
    -   within redistribute config line
    -   with Route Map (**PREFERRED** if multiple are configured, then distribute command metric then default-metric)
-   Redistributed **Static Routes** appear in neighbors route tables as **Externals**.

### OSPF

-   Redistribution can happen anywhere except aside from stubby, totally stubby networks - redistributing router becomes ASBR and has type 4 LSA advertised to any areas outside of its own local area to ensure reachability to border router
-   External routes will be Type 5 LSA in regular area, Type 7LSA in NSSA and translated to type 5 at ABR
-   By default routes will be external type 2, e1 always preferred over e2 in OSPF algorithm
-   Must use the `subnets` flag or only classful routes will be redistributed.

### BGP

-   No seed metric required
-   Don't redistribute eBGP into IGP as they can't handle the volume of routes
-   Use `bgp redistribute-internal` to force BGP to redistribute iBGP routers into another IGP
-   Origin set to incomplete, Weight to 32768, MED to path metric of source protocol
-   Redistribution from OSPF to BGP doesn't include OSPF External routes by default
    -   must user `match external [1|2]` to redistribute OSPF externals
    -   Note if you use `external` only this **ONLY** redistributes externals.

------------------------------------------------------------------------

## Configuration

### Route Map

### EIGRP

``` default
router eigrp 100
 default-metric 1000000 1 255 1 1500
 network 10.23.1.0 0.0.0.255
 redistribute ospf 1
 distance 165 10.1.1.1 0.0.0.0                                       (Changes AD for external (redistributed) routes)
 distance 165 170                                                   (sets AD for internal then external routes)
-------------------------------------

router eigrp EIGRP-NAMED
 addres-family ipv4
  default-metric 1000000 1 255 1 1500
  redistribute ospf 1
 exit-af-topology
 network 10.23.1.0 0.0.0.255
-------------------------------------

router eigrp EIGRP-NAMED
 addres-family ipv4
  redistribute bgp 65100 metric 1000000 1 255 1 1500
 exit-af-topology
 network 10.23.1.0 0.0.0.255
-------------------------------------

!!! With Route Map Setting Metric !!!
router eigrp 100
 network 10.23.1.0 0.0.0.255
 redistribute ospf 1 route-map OSPF-2-EIGRP
 
route-map OSPF-2-EIGRP permit 10
 set metric 1000000 1 255 1 1500
```

### OSPF

``` default
router ospf 2
 network 10.41.1.0 0.0.0.255 area 0
 redistribute eigrp 100 subnets                             (allows classless network redistribution from EIGRP)
 distance ospf external 171                                 ! for AD manipulation if required
 
 
```

### BGP

``` default
router bgp 65100
  address-family ipv4
    redistribute connected route-map RM-LOOPBACK
!
route-map RM-LOOPBACK
  match interface Loopback0
  
----
redistribute connected / static etc.
redistrivute ospf 100 match external 1 external 2                                               - Redistributes OSPF E1 + E2

distance bgp external-ad internal-ad local-routes             Sets AD for network types
distance AD source-ip source-wildcardmask                     Sets AD of routes learned from IP
```

------------------------------------------------------------------------

## Useful Show Commands

`show ip protocol` - shows redistribution under each protocol

`show ip route profile` -
