---
title: "Route Maps & PBR"
editor: visual
code-block-bg: dark
---

## Policy Based Routing

-   PBR intercept packet before regular routing, **INGRESS ONLY**
-   Makes use of **Route-Maps**
-   Doesn't process packets locally generated by the router itself by default
    -   Use `local` keyword and apply at global level to enable this

        -   `ip local policy route-map [route-map name]`
-   Conditional forwarding of packets based on something other than destination IP
    -   Outgoing int (if point-to-point)
    -   IP Next Hop
    -   TCP/UDP Header
-   Downsides are operational complexity, increased load on router
-   Can specify multiple next-hops - when done the first will be used if the next-hop is adjacent, otherwise it will use the second, third, etc
-   If you want to use a non-adjacent route, you must use the `recursive` flag when configuring the route-map `set` statement
-   Config options:
    -   `set ip next-hop ip-address [ip]` - sets next hop IP - doesn't verify reachability, if next hop unreachable the packets are dropped.
    -   `set ip next hop recursive 10.1.1.1` - tells the router to use the routing table to find the next hop interface towards 10.1.1.1
    -   `set ip next-hop verify-availability 10.1.1.1 1 track 10` - Verifies reachability via tracking/IPSLA, if next hop down PBR entry is skipped, packet routed by RIB
    -   `set ip default next-hop ip-address [ip]` - `default` - Fallback, - if routing table has a match for destination it wins, if no route exists - configred next hop wins.
        -   If destination **exists in route table**: the command doesn't policy route, routes based on routing table
        -   If destination **does not** **exist in route table**: the command policy routes the packet to the next hop.
    -   `set interface [interface type] [interface-number]` (multiple ints will be tried in turn)
    -   `set default interface [interface type] [interface-number]`
-   Using the `default` flag causes next-hop value to be set only for routes not within the router’s RIB
-   Can also combine PBR with [IP SLA & Tracking](https://brunbattery.github.io/NetworkNotes/IP%20SLA%20&%20Tracking.html) to ensure reachability of next-hops

## ACLs

-   ACL Subnet Mask - IGP's use this to define the smallest prefix length, BGP uses it to match the subnet mask for the route

-   Standard ACL **(1-99, 1300-1999)**: Defines based solely on source network

-   Extended ACL **(100-100, 2000-2699)** : Defines based on source, destination, protocol, port or combination of other packet attributes.

-   Either can be Named

-   ipv6 EIGRP distribute-lists can ONLY match on prefix-lists and route-maps (not acls, )

## Route-Maps

-   When Multiple Match statements exist in a single RM sequence
    -   If both statements match different criteria = logical **AND**
    -   If both statements match the same criteria = logical **OR**
-   When referenced by a Route Map, Permit in ACL means go ahead and process this matched traffic however the route map likes.
-   Route-map goes through sequences until a match is found then stops unless the `continue` flag is set
-   When using an ACL the ACL cannot contain `time-range`, `disable-port` or `log-input.`
-   Clauses Evaluated in this order
    -   `set ip next-hop`
    -   `set interface`
    -   `set ip default next-hop`
    -   `set default interface`

## 

## Config

### Prefix Lists

``` default
PRefix list matchign default route
 ipv4: ip prefix-list DEFAULTROUTE permit 0.0.0.0/0                          (The quad 0 matches anything the /0 only matches the default route)
 ipv6: ip prefix-list DEFAULTROUTE permit ::/0

Prefix list matching all routes
 ipv4: ip prefix-list ALLROUTES permit 0.0.0.0/0 le32                        (The quad 0 matches anything and the le32 states so long as the mask is less than 32)
 ipv5: ip prefix-list ALLROUTES permit ::/0 le 128

 Example
 ip prefix-list DENY_30 deny 0.0.0.0/0 ge30 le30                            - This matches and denies all /30 routes (point-to-point)
 ip prefix-list DENY_30 permit 0.0.0.0/0 le32                               - This matches and permits all other routes.
```

### PBR

``` default
ip access-list extended PBR_UK
 permit ip 10.44.1.0 0.0.0.255 10.1.0.0 0.0.0.255
!
route-map RM_PBR_GLASGOW permit 10
 match ip address PBR_UK
 set ip [default] next-hop 10.44.255.1 [optional second IP]
!
interface GigabitEthernet0/1
 ip policy route-map RM_PBR_GLASGOW
```

PBR with IP SLA & Tracking

``` default
ip sla 1
icmp-echo 10.44.1.1
ip sla schedule 1 life forever start-time now
!
track 1 ip sla 1 reachability
!
ip access-list standard ACL
 permit ip 10.1.1.10/32 10.2.2.10/32
!
route-map PBR-NEXTHOP
 match ip address ACL
 set ip next-hop verify-availability 10.44.1.1 track 1
!
interface GigabitEthernet0/1
 ip policy route-map PBR-NEXTHOP
```

## Useful Show Commands

-   `show ip policy`
-   `show route-map`
-   `traceroute x.x.x.x`
-   `debug ip policy`
